name: Build and Deploy FastAPI to Azure Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Zip deployment package
        run: |
          zip -r release.zip . -x "*.git*" "*.github*" ".venv/*"

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip deployment package
        run: |
          unzip release.zip
          rm release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_105FEC104AAA44F7AE871052FBC981B5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_78A9D211BB9241C9B37A63BE7B448F92 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1ECAEEF5F1CC4AC18A2B49D26FF64770 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'azf-py-func'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
